POST http://localhost:3000/api/auth/register
Content-Type: application/json

  {                                                                                   
    "username": "test",
    "email": "test@test.com",                                                         
    "password": "parola123",                                                          
    "cityName": "Roma"      
  }    

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

  {                                                                                   
    "username": "test1",
    "email": "test1@test.com",                                                         
    "password": "parola123",                                                          
    "cityName": "Roma"      
  }    

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

  {
    "email": "test@test.com",
    "password": "parola123"
  }

###

# Upgrade cladire
# 1. Fa login mai sus si copiaza token-ul
# 2. Gaseste buildingId: SELECT id, name, level FROM "Building" WHERE "cityId" = '...';
POST http://localhost:3000/api/buildings/d88804c0-e2d1-4536-bb30-7f8538c38bac/upgrade
Authorization: Bearer .eyJpZCI6IjRkOTFlZTdhLTliN2ItNDIwYS1iYmU3LTQyZDQwYTZkYjg4MyIsImlhdCI6MTc3NDg4Njc0MCwiZXhwIjoxNzc1NDkxNTQwfQ._1QVF-tovBNw34ryvwdXf1JLET7Dn7MYmHOUq6-DcF4

###
