POST http://localhost:3000/api/auth/register
Content-Type: application/json

  {                                                                                   
    "username": "test",
    "email": "test@test.com",                                                         
    "password": "parola123",                                                          
    "cityName": "Roma"      
  }    

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

  {                                                                                   
    "username": "test1",
    "email": "test1@test.com",                                                         
    "password": "parola123",                                                          
    "cityName": "Roma"      
  }    

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

  {                                                                                   
    "email": "test@test.com",
    "password": "parola123"
  }

###

